export { default as UploadFile } from "./UploadFile";
export { default as Sidebar } from "./Sidebar";
export { default as Clubs } from "./Clubs";
export { default as Course } from "./Course";
export { default as Department } from "./Department";
export { default as Download } from "./Download";
export { default as Staff } from "./Staff";
export { default as Student } from "./Student";
export { default as Admind } from "./Admin";